"use client";
import { FormEvent, useState } from "react";
import { Bot, Building2, CalendarCheck, CalendarDays, LoaderCircle, Send, Sparkles } from "lucide-react";
import { ActionResponse, AgentRunResponse, api } from "@/lib/api";
type Message={role:"assistant"|"user";content:string};
export default function ChatPanel({onTripPlanned}:{onTripPlanned?:()=>void}){
  const [messages,setMessages]=useState<Message[]>([{role:"assistant",content:"Tell me your destination, dates, budget, travelers, and preferences."}]); const [input,setInput]=useState(""); const [loading,setLoading]=useState(false); const [result,setResult]=useState<AgentRunResponse|null>(null); const [threadId,setThreadId]=useState<string|null>(null); const [error,setError]=useState(""); const [actionStatus,setActionStatus]=useState("");
  async function send(event:FormEvent){event.preventDefault();const prompt=input.trim();if(!prompt||loading)return;setMessages(x=>[...x,{role:"user",content:prompt}]);setInput("");setLoading(true);setError("");setActionStatus("");try{const response=await api<AgentRunResponse>("/agent/run",{method:"POST",body:JSON.stringify({prompt,thread_id:threadId,timezone:Intl.DateTimeFormat().resolvedOptions().timeZone||"UTC"})});setResult(response);setThreadId(response.thread_id);setMessages(x=>[...x,{role:"assistant",content:response.plan.summary}]);onTripPlanned?.();}catch(e){setError(e instanceof Error?e.message:"Agent workflow failed");}finally{setLoading(false);}}
  async function decide(decision:"approve"|"reject"){if(!result?.pending_action_id)return;setLoading(true);setError("");try{const response=await api<ActionResponse>(`/agent/actions/${result.pending_action_id}/${decision}`,{method:"POST"});setActionStatus(response.status==="approved"?`Added to Google Calendar${response.result?.html_link?` — ${response.result.html_link}`:""}`:"Calendar action rejected");}catch(e){setError(e instanceof Error?e.message:"Action failed");}finally{setLoading(false);}}
  return <section className="panel chatPanel"><div className="panelTitle"><span className="iconBox"><Bot size={18}/></span><div><h2>TripPilot Agent</h2><p>LangGraph · Hotel MCP · Calendar MCP · Memory</p></div></div><div className="messages">{messages.map((m,i)=><div key={i} className={`message ${m.role}`}>{m.content}</div>)}{loading&&<div className="agentLoading"><LoaderCircle size={17}/> Running agent workflow...</div>}{error&&<div className="error">{error}</div>}{result&&<div className="planResult"><div className="resultHeading"><Sparkles size={17}/><b>{result.plan.destination}</b><span>{result.plan.currency} {Number(result.plan.total_budget).toLocaleString()}</span></div><div className="planMeta"><span><CalendarDays size={14}/>{result.plan.start_date} — {result.plan.end_date}</span><span>{result.review.valid?"Review passed":"Needs attention"}</span></div>{result.review.issues.length>0&&<div className="reviewIssues">{result.review.issues.map(issue=><small key={issue}>• {issue}</small>)}</div>}<div className="dayChips">{result.plan.days.map(day=><span key={day.day}>Day {day.day}: {day.theme}</span>)}</div>{result.hotels.length>0&&<div className="hotelResults"><h3><Building2 size={16}/> Live hotel offers</h3>{result.hotels.map(hotel=><article key={hotel.hotel_id}><div><b>{hotel.name}</b><small>{hotel.rating?`${hotel.rating}-star · `:""}{hotel.room_description||"Available room"}</small></div><strong>{hotel.currency} {Number(hotel.price_total).toLocaleString()}</strong></article>)}</div>}{result.requires_approval&&!actionStatus&&<div className="approvalCard"><CalendarCheck size={18}/><div><b>Add trip to Google Calendar?</b><small>Nothing is created until you approve.</small></div><button className="primary" onClick={()=>decide("approve")}>Approve</button><button className="secondary" onClick={()=>decide("reject")}>Reject</button></div>}{actionStatus&&<div className="success">{actionStatus}</div>}</div>}</div><form className="chatInput" onSubmit={send}><input value={input} onChange={e=>setInput(e.target.value)} placeholder="Plan 4 days in Singapore under $800..."/><button aria-label="Send" disabled={loading}><Send size={17}/></button></form></section>;
}
