"use client";
import { useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { CalendarDays, LogOut, Map, Sparkles, Wallet } from "lucide-react";
import ChatPanel from "@/components/ChatPanel";
import NewTripForm from "@/components/NewTripForm";
import { api, Trip, User } from "@/lib/api";
export default function Dashboard(){const router=useRouter();const [user,setUser]=useState<User|null>(null);const [trips,setTrips]=useState<Trip[]>([]);const [loading,setLoading]=useState(true);useEffect(()=>{Promise.all([api<User>("/auth/me"),api<Trip[]>("/trips")]).then(([u,t])=>{setUser(u);setTrips(t)}).catch(()=>{localStorage.removeItem("token");router.replace("/login")}).finally(()=>setLoading(false))},[router]);function logout(){localStorage.removeItem("token");router.push("/")}if(loading)return <main className="loading"><Sparkles/> Loading your journeys...</main>;return <main className="dashboard"><aside><div className="brand"><Sparkles size={21}/> TripPilot <span>AI</span></div><nav><a className="active"><Map size={18}/> Overview</a><a><CalendarDays size={18}/> My trips</a></nav><button className="logout" onClick={logout}><LogOut size={17}/> Sign out</button></aside><div className="content"><header><div><p className="kicker">TRAVEL DASHBOARD</p><h1>Welcome, {user?.name.split(" ")[0]}</h1><p>Ready to turn another idea into a journey?</p></div><NewTripForm onCreated={t=>setTrips(x=>[t,...x])}/></header><div className="stats"><div><Map size={19}/><span><b>{trips.length}</b> Total trips</span></div><div><CalendarDays size={19}/><span><b>{trips.filter(t=>t.status==="planned").length}</b> Planned</span></div><div><Wallet size={19}/><span><b>{trips.length?trips[0].currency:"USD"}</b> Default currency</span></div></div><div className="grid"><ChatPanel/><section className="panel tripsPanel"><div className="panelTitle"><div><h2>Recent trips</h2><p>Your saved travel plans</p></div></div>{trips.length===0?<div className="empty"><Map size={35}/><h3>No trips yet</h3><p>Create one to start your travel history.</p></div>:<div className="tripList">{trips.slice(0,6).map(t=><article key={t.id}><div className="tripIcon">{t.destination.charAt(0)}</div><div><h3>{t.destination}</h3><p>{new Date(t.start_date+"T00:00:00").toLocaleDateString(undefined,{month:"short",day:"numeric"})} — {new Date(t.end_date+"T00:00:00").toLocaleDateString(undefined,{month:"short",day:"numeric"})}</p></div><div className="tripBudget">{t.currency} {Number(t.budget).toLocaleString()}<span>{t.status}</span></div></article>)}</div>}</section></div></div></main>}

